export const DOC_SECTIONS = [
  { id: 'installation',            label: 'Installation' },
  { id: 'initialization',          label: 'Initialization' },
  { id: 'commit-interview',        label: 'Commit Interview' },
  { id: 'pausing-and-disabling',   label: 'Pausing & Disabling' },
  { id: 'real-time-file-watcher',  label: 'Real-time Watcher' },
  { id: 'viewing-your-log',        label: 'Viewing Your Log' },
  { id: 'recording-decisions',     label: 'Recording Decisions' },
  { id: 'revert-post-mortems',     label: 'Revert Post-Mortems' },
  { id: 'end-of-day-reflection',   label: 'End-of-Day Reflection' },
  { id: 'statistics',              label: 'Statistics & Analytics' },
  { id: 'exporting-data',          label: 'Exporting Data' },
  { id: 'configuration',           label: 'Configuration Reference' },
  { id: 'database-reference',      label: 'Database Reference' },
  { id: 'git-hooks-reference',     label: 'Git Hooks Reference' },
  { id: 'answer-tagging',          label: 'Answer Tagging' },
  { id: 'complexity-scoring',      label: 'Complexity Scoring' },
  { id: 'windows-notes',           label: 'Windows Notes' },
];
